--- #YAML:1.0
name:               WWW-Grooveshark
version:            0.01
abstract:           Perl wrapper for the Grooveshark API
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Digest::MD5:     0
    Exporter:        0
    JSON::Any:       0
    LWP::UserAgent:  0
    NEXT:            0.61
    perl:            5.006
resources:
    repository:  http://elementsofpuzzle.googlecode.com/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
